kafka:
  bootstrap-servers: localhost:9092
  enable: true
  topics:
    rcs-submission: rcs-submission-events-test
    rcs-response: rcs-response-events-test
  consumers:
    rcs-submission:
      enable: true
      id: rcs-submission-listener-id-test
      group-id: rcs-submission-group-id-test
    rcs-response:
      enable: true
      id: rcs-response-listener-id-test
      group-id: rcs-response-group-id-test