kafka:
  bootstrap-servers: 13.204.28.222:9092
  enabled: true
  topics:
    rcs-submission: rcs-submission-events-local
    rcs-response: rcs-response-events-local
  consumers:
    rcs-submission:
      enabled: true
      id: rcs-submission-listener-id-local
      group-id: rcs-submission-group-id-local
    rcs-response:
      enabled: true
      id: rcs-response-listener-id-local
      group-id: rcs-response-group-id-local

