spring:
  datasource:
    url: jdbc:postgresql://13.204.28.222:5432/messagefusion_db
    username: postgres
    password: B3Fu4Ao5BJ8Bb1D
    driver-class-name: org.postgresql.Driver

kafka:
  bootstrap-servers: localhost:9092
  enabled: true
  topics:
    rcs-submission: rcs-submission-events-test
    rcs-response: rcs-response-events-test
  consumers:
    rcs-submission:
      enabled: true
      id: rcs-submission-listener-id-test
      group-id: rcs-submission-group-id-test
    rcs-response:
      enabled: true
      id: rcs-response-listener-id-test
      group-id: rcs-response-group-id-test