kafka:
  bootstrap-servers: localhost:9092
  enable: true
  topics:
    rcs-submission: rcs-submission-events-prod
    rcs-response: rcs-response-events-prod
  consumers:
    rcs-submission:
      enable: true
      id: rcs-submission-listener-id-prod
      group-id: rcs-submission-group-id-prod
    rcs-response:
      enable: true
      id: rcs-response-listener-id-prod
      group-id: rcs-response-group-id-prod