spring:
  application:
    name: messaging-processor
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: ["loggers"]
  metrics:
    kafka:
      enabled: true
    export:
      prometheus:
        enabled: true

